server.port=8888
spring.application.name=config-server
spring.cloud.config.server.git.uri=https://github.com/Saumya-tripathi/spring-config-properties
spring.cloud.config.server.git.username=Saumya-tripathi
spring.cloud.config.server.git.password=token
logging.level.root=info
logging.level.org.springframework.web=DEBUG

