server.port=8888
spring.application.name=config-server
spring.cloud.config.server.git.uri=https://github.com/Saumya-tripathi/spring-config-properties
spring.cloud.config.username=Saumya-tripathi
spring.cloud.config.password=ghp_9n2m8s1v7a39a2b1c8e5f0d9c8e7a
logging.level.root: INFO
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR